### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by ilanbiala**
Test aginst Node 0.12 as well.

### CODE REVIEW

**Comment by ilanbiala** [comment]
@terinjokes any reason not to merge this?

**Comment by terinjokes** [comment]
I'm on vacation.

**Comment by ilanbiala** [comment]
Bump...

**Comment by ilanbiala** [comment]
@terinjokes can this be merged? Why not?

**Comment by terinjokes** [comment]
Edited on master to also include iojs.

**Pull request closed without merging**
