### PR TITLE
Custom error handler

### LINKED ISSUE #110: Switch to suppress parse errors
When using components fe. from Bower (which might come with source files split to different files, or any broken files for building etc) the possible parse errors in any random file kills the whole minifying process and you have to separately remove them from source files.

For cases like this it would be handy if `gulp-uglify` would have `supressErrors` option, which, instead of triggering error on parse issues (which ends the whole process), would just console.log out a warning, skip that file and keep chugging along. Much like r.js does it. (Except that it doesn't even show any warnings)

Uglify itself doesn't have switch for this since the recommended way to do this in uglify would be to wrap the call in try-catch block. https://github.com/mishoo/UglifyJS2/issues/620

### PR DESCRIPTION
**Pull request by mikkotikkanen**
Fixes #110

### CODE REVIEW

**Comment by mikkotikkanen** [comment]
@terinjokes Any updates on this? I think this would be quiet a handy way to solve those pesky edge cases.

**Comment by terinjokes** [comment]
@mikkotikkanen GitHub did not notify me 8 days ago, so I'm just now seeing this.

**Comment by mikkotikkanen** [comment]
kk :)

**Comment by bradvogel** [comment]
+1

**Comment by stanier** [comment]
+1

**Comment by terinjokes** [comment]
There's no advantage to using this compared to handling the error event.

**Comment by mikkotikkanen** [comment]
Eh. The whole point was to be able to handle cases where you DON'T want it to go to the error handler

**Pull request closed without merging**
