### PR TITLE
Fix the case where generated source maps has a null source content

### PR DESCRIPTION
**Pull request by zaygraveyard**
which leads to a "Ghost" source file as described by @mircolino in #109

### CODE REVIEW

**Comment by terinjokes** [comment]
Can you reproduce the issue in the tests without requiring `babel` and `gulp-babel`?

**Comment by zaygraveyard** [comment]
Is it better now?

**Comment by zaygraveyard** [comment]
I removed `babel` and `gulp-babel` from the requirements by pre-compiling the test code with babel.
Is this acceptable?
Thanks

**Comment by terinjokes** [comment]
@zaygraveyard my apologies. I've been busy the last little bit, and I haven't gotten a chance to review and test this.

**Comment by terinjokes** [comment]
Thanks for your contributions. Merged as https://github.com/terinjokes/gulp-uglify/commit/05551819ddba3c73f80ece0422a0e4d4e67073f5.

**Pull request closed without merging**
