### PR TITLE
Support parallel execution of transforms. (fixes #72)

### LINKED ISSUE #72: is there a way to invoke in parallel mode to use multiple cpu cores for faster builds?
I'm wondering if this is possible with gulp-uglify. Or maybe just uglify in general

### PR DESCRIPTION
**Pull request by schnittstabil**
Cribbed from [terinjokes/gulp-closure](https://github.com/terinjokes/gulp-closure).

### CODE REVIEW

**Comment by terinjokes** [comment]
I don't believe this changes anything: the individual minification tasks are still synchronous, where in gulp-closure they are asynchronously asynchronous.

**Comment by schnittstabil** [comment]
Yeah, sorry, I missed the `setImmediate`.

But I also reconsidered the problem and have to conclude that gulp-uglify actually don't benefit much from such efforts, because:
* `gulp.src` reads the whole file content
* highWaterMark and back-pressure regulate the file stream in an optimal way
* Node runs in a single thread on a single cpu(!?) - `nextTick`, `setImmediate` and `setTimeout` can't change this
* `cluster.fork()` won't help, it forks a new _process_ (process communication for a gulp plugin seems overkill)

Maybe I miss something...

**Comment by terinjokes** [comment]
@schnittstabil indeed, all the reasons why I didn't implement this. :)

It works in gulp-closure because the minification happens outside of Node, asynchronous to the JavaScript execution.

**Comment by wjordan** [comment]
(Commenting here because the [issue thread](https://github.com/terinjokes/gulp-uglify/issues/72) was locked before I could contribute a response to the comment that this feature is now considered [out of scope](https://github.com/terinjokes/gulp-uglify/issues/72#issuecomment-152181367) for this project.)

The [reasons](https://github.com/gulpjs/gulp/issues/317#issuecomment-149336502) why `child_process`-based default tasks are outside the scope of Gulp itself are that the increased memory requirements and per-process spawning times are not ideal for a framework-wide default to be applied to all tasks within the Gulp ecosystem, so the currently-recommended scope for multi-core features is for them to ['stay in userland'](https://github.com/gulpjs/gulp/issues/317#issuecomment-149437711).

`gulp-uglify` _is_ a 'userland' plugin. In many use-cases, the increased memory requirements and per-process spawning times are small in comparison to the performance gains achieved by running multiple `uglify` tasks in parallel (I have observed these gains in practice). Because there is a performance-tradeoff involved that doesn't simply satisfy _all_ use-cases, there's room for discussion around whether a multi-process feature should be on/off by default, toggled via config option, and/or chosen by a more advanced heuristic. I don't think this alone would justify such a feature being considered out of scope for this project, however (particularly when many users have expressed interest in it).

I'll also respond to the [above reasons](https://github.com/terinjokes/gulp-uglify/pull/79#issuecomment-70745575) in order:
- the file content read by `gulp.src` can be passed to the child process as a string with negligible overhead, and `UglifyJS` supports compressing a JavaScript string directly.
- the file stream can still be optimally processed in parallel using `parallel-transform`.
- `child_process` allows parallel execution within Node.
- existing npm modules simplify the complexity of inter-process communication, making it not 'overkill' to implement.

That should cover all of the reasons mentioned, let me know if there's anything further I can add to the discussion.

**Comment by terinjokes** [comment]
@wjordan My understanding of "stay in userland" is that someone creates a plugin to Gulp that has a scheme to work on tasks or files in parallel where transforming plugins would just work, not to hound every plugin author to add parallelism individually to their plugins.

I don't make many assumptions about the environment `gulp-uglify` is running in. Fill free to experiment with ways of spawning and feeding it Vinyl instances. But it is not something I'm going to be adding myself.

**Pull request closed without merging**
